// This file is automatically generated. Do not modify it manually.

package plugin

var manifest = struct {
	ID      string
	Version string
}{
	ID:      "sshindanai.google-calendar-plugin",
	Version: "0.1.0",
}
